DATABASE:
  DRIVER: "postgres"
  HOST: "localhost"
  PORT: 5432
  USERNAME: ""
  PASSWORD: ""
  DATABASE: ""

SERVICE:
  HOST: "localhost"
  PORT: 6969

SERVER:
  SHUTDOWN:
    CLEANUP_PERIOD_SECONDS: "10"
    GRACE_PERIOD_SECONDS: "10"